const cookieParser = require("cookie-parser");
const cors = require('cors');
const { v4: uuid } = require("uuid");
const express = require("express");
const app = express();
const port = 3001;

const mainRoute = require("./routes/routes");
const clientes = require("./routes/clientes.routes");
const produtos = require("./routes/produtos.routes");
const usuario = require("./routes/usuario.routes");
const estoque = require("./routes/estoque.routes");
const fabricante = require("./routes/fabricante.routes");
const transportadora = require("./routes/transportadora.routes");
const codBarra = require("./routes/codBarra.routes");
const conta = require("./routes/conta.routes");
const funcionario = require("./routes/funcionario.routes");
const cidade = require("./routes/cidade.routes");
const etiqueta = require("./routes/etiqueta.routes");
const loja = require("./routes/loja.routes");
const unidade = require("./routes/unidade.routes");
const fornecedor = require('./routes/fornecedor.routes');
const admCartao = require('./routes/admCartao.routes');
const agencia = require('./routes/agencia.routes');
const banco = require('./routes/banco.routes');
const cargo = require('./routes/cargo.routes');
const cartao = require('./routes/cartao.routes');
const centroCusto = require('./routes/centroCusto.routes');
const grupoPreco = require('./routes/grupoPreco.routes');
const grupoProduto = require('./routes/grupoProduto.routes');
const planoConta = require('./routes/planoConta.routes');
const servico = require('./routes/servico.routes');
const tipoServico = require('./routes/tipoServico.routes');
const tipoDespesa = require('./routes/tipoDespesa.routes');
const subGrupoProduto = require('./routes/subGrupoProduto.routes');
const produtoRapido = require('./routes/produtoRapido.routes');
const promocao = require('./routes/promocao.routes');
const produtoFornecedor = require('./routes/produtoFornecedor.routes');
const produtoSecao = require('./routes/produtoSecao.routes');
const cartaoConvenio = require('./routes/cartaoConvenio.routes');
const afericao = require('./routes/afericao.routes');
const agendarBico = require('./routes/agendarBico.routes');
const cep = require('./routes/cep.routes');
const cest = require('./routes/cest.routes');
const entrega = require('./routes/entrega.routes');
const estoqueGeral = require('./routes/estoqueGeral.routes');
const lote = require('./routes/lote.routes');
const ncm = require('./routes/ncm.routes');
const observacao = require('./routes/observacao.routes');
const veiculo = require('./routes/veiculo.routes');
const transacao = require('./routes/transacao.routes');
const tipoCombustivel = require('./routes/tipoCombustivel.routes');
const tipoItem = require('./routes/tipoItem.routes');
const tipoPagto = require('./routes/tipoPagto.routes');
const segmento = require('./routes/segmento.routes');
const cotacao = require('./routes/cotacao.routes');
const classFiscal = require('./routes/classFiscal.routes');
const classFiscalImpressora = require('./routes/classFiscalImpressora.routes');
const estacao = require('./routes/estacao.routes');
const impressora = require('./routes/impressora.routes');
const listaPositivo = require('./routes/listaPositivo.routes');
const listaPsico = require('./routes/listaPsico.routes');
const encomendaCab = require('./routes/encomendaCab.routes');
const contabilista = require('./routes/contabilista.routes');
const contaContabil = require('./routes/contaContabil.routes');
const grupoProibidoEmpresa = require('./routes/grupoProibidoEmpresa.routes');
const icms = require('./routes/icms.routes');
const ibpt = require('./routes/ibpt.routes');
const grupoDescontoEmpresa = require('./routes/grupoDescontoEmpresa.routes');
const grupoPermissao = require('./routes/grupoPermissao.routes');
const dependenteCliente = require('./routes/dependenteCliente.routes');
const abastecimento = require('./routes/abastecimento.routes');
const aguaLuz = require('./routes/aguaLuz.routes');
const alteracaoEstoque = require('./routes/alteracaoEstoque.routes');
const analiseTributacao = require('./routes/analiseTributacao.routes');
const anp = require('./routes/anp.routes');
const anvisa = require('./routes/anvisa.routes');
const apuracaoICMS = require('./routes/apuracaoICMS.routes');
const atualizacaoPreco = require('./routes/atualizacaoPreco.routes');
const cfFarmaceutico = require('./routes/cfFarmaceutico.routes');
const cfop = require('./routes/cfop.routes');
const cheque = require('./routes/cheque.routes');
const cheque2 = require('./routes/cheque2.routes');
const clienteDescProduto = require('./routes/clienteDescProduto.routes');
const clienteEndereco = require('./routes/clienteEndereco.routes');
const csosn = require('./routes/csosn.routes');
const cst = require('./routes/cst.routes');
const cstpiscofins = require('./routes/cstpiscofins.routes');
const bico = require('./routes/bico.routes');
const boleto = require('./routes/boleto.routes');
const comunicacaoBico = require('./routes/comunicacaoBico.routes');
const condicaoPagamento = require('./routes/condicaoPagamento.routes');
const condicaoParcelamento = require('./routes/condicaoParcelamento.routes');
const configSped = require('./routes/configSped.routes');
const dav = require('./routes/dav.routes');
const dcbs = require('./routes/dcbs.routes');
const ecfCupomCab = require('./routes/ecfCupomCab.routes');
const ecfMovimento = require('./routes/ecfMovimento.routes');
const emails = require('./routes/emails.routes');
const escaneados = require('./routes/escaneados.routes');
const exportaBalanca = require('./routes/exportaBalanca.routes');
const faixaVencimento = require('./routes/faixaVencimento.routes');
const indicacao = require('./routes/indicacao.routes');
const infoComplementares = require('./routes/infoComplementares.routes');
const lmcDet = require('./routes/lmcDet.routes');
const lmcEstoque = require('./routes/lmcEstoque.routes');
const lmcInterven = require('./routes/lmcInterven.routes');
const lmcIntervenBico = require('./routes/lmcIntervenBico.routes');
const log = require('./routes/log.routes');
const compraSugestao = require('./routes/compraSugestao.routes');
const compra4 = require('./routes/compra4.routes');
const conhecimentoTransporte = require('./routes/conhecimentoTransporte.routes');
const compraSugestao2 = require('./routes/compraSugestao2.routes');
const contasPagar = require('./routes/contasPagar.routes');
const curvaABC = require('./routes/curvaABC.routes');
const encomenda = require('./routes/encomenda.routes');
const fatura = require('./routes/fatura.routes');
const lfInventario = require('./routes/lfInventario.routes');
const lfInventario2 = require('./routes/lfInventario2.routes');
const lfInventario3 = require('./routes/lfInventario3.routes');
const inventario = require('./routes/inventario.routes');
const lancamentoDiverso = require('./routes/lancamentoDiverso.routes');
const lancamentoFuncionario = require('./routes/lancamentoFuncionario.routes');
const notaM1 = require('./routes/notaM1.routes');
const movCartao = require('./routes/movCartao.routes');
const telecomunicacao = require('./routes/telecomunicacao.routes');
const notaServico = require('./routes/notaServico.routes');
const seried = require('./routes/seried.routes');
const pedido = require('./routes/pedido.routes');
const nfeCabecalho4 = require('./routes/nfeCabecalho4.routes');
const totalizador = require('./routes/totalizador.routes');
const tanqueMedicao = require('./routes/tanqueMedicao.routes');
const relatorio = require('./routes/relatorio.routes');
const receita = require('./routes/receita.routes');
const recarga = require('./routes/recarga.routes');
const profSaude = require('./routes/profSaude.routes');
const produtoDlg = require('./routes/produtoDlg.routes');
const principioAtivo = require('./routes/principioAtivo.routes');
const periodoContabilista = require('./routes/periodoContabilista.routes');
const contasReceber = require('./routes/contasReceber.routes');
const prevenda = require('./routes/prevenda.routes');
const pbms = require('./routes/pbms.routes');
const pbm = require('./routes/pbm.routes');
const ncmSecao = require('./routes/ncmSecao.routes');
const ncmPosicao = require('./routes/ncmPosicao.routes');
const ncmGenero = require('./routes/ncmGenero.routes');
const naturezaReceita = require('./routes/naturezaReceita.routes');
const naturezaOP = require('./routes/naturezaOP.routes');
const msgCliente = require('./routes/msgCliente.routes');
const movimentacaoCaixa = require('./routes/movimentacaoCaixa.routes');
const movConta = require('./routes/movConta.routes');
const modelosFiscais = require('./routes/modelosFiscais.routes');
const menu = require('./routes/menu.routes');
const ecfReducao = require('./routes/ecfReducao.routes');
const ecfImpressora = require('./routes/ecfImpressora.routes');
const tanque = require('./routes/tanque.routes');
const sintegra = require('./routes/sintegra.routes');
const registro60 = require('./routes/registro60.routes');
const rede = require('./routes/rede.routes');
const logBuscaBico = require('./routes/logBuscaBico.routes');
const livroLMC = require('./routes/livroLMC.routes');
const fechamentoCaixa = require('./routes/fechamentoCaixa.routes');
const exportacao = require('./routes/exportacao.routes');
const encerrante = require('./routes/encerrante.routes');
const empresaConveniada = require('./routes/empresaConveniada.routes');
const dash = require('./routes/dash.routes');
const bomba = require('./routes/bomba.routes');
const balancoGeral = require('./routes/balancoGeral.routes');
const spedCofins = require('./routes/spedCofins.routes');
const sped = require('./routes/sped.routes');
const mensagem = require('./routes/mensagem.routes');
const gerarLMC = require('./routes/gerarLMC.routes');
const movimento = require('./routes/movimento.routes');
const movimentacaoSNGPC = require('./routes/movimentacaoSNGPC.routes');
const movimentacaoSNGPC2 = require('./routes/movimentacaoSNGPC2.routes');
const turno = require('./routes/turno.routes');
const MDFe = require('./routes/MDFe.routes');
const vendas = require('./routes/vendas.routes');
const cte = require('./routes/cte.routes');
const boletoWs = require('./routes/boletoWs.routes');
const configBoleto = require('./routes/configBoleto.routes');

// const requireAuth = function (req, res, next) {
//     if (!req.cookies.auth) {
//         const auth = uuid();
//         if (!req.cookies.auth) {
//             res.cookie("auth", auth);
//         }
//         res.status(200).json({ auth });
//     }
//     next();
// };

app.use(cors());
app.use(express.json());
app.use(cookieParser());
app.use(function (req, res, next) {
    res.setHeader("Access-Control-Allow-Origin", "*");
    res.setHeader("Access-Control-Allow-Methods", "GET,POST,PUT,DELETE,OPTIONS");
    res.setHeader(
        "Access-Control-Allow-Headers",
        "Content-Type, Access-Control-Allow-Headers"
    );

    next();
});

const auth = express.Router();

// auth.all("*", requireAuth);

// localhost/api/v1/
auth.use("/", (req, res, next) => {
    if (req.cookies) {
        next();
    } else {
        res.send({ error: "Invalid credentials" });
    }
});

auth.use('/abastecimento', abastecimento);
auth.use('/admCartao', admCartao);
auth.use('/afericao', afericao);
auth.use('/agencia', agencia);
auth.use('/agendarBico', agendarBico);
auth.use('/aguaLuz', aguaLuz);
auth.use('/alteracaoEstoque', alteracaoEstoque);
auth.use('/analiseTributacao', analiseTributacao);
auth.use('/anp', anp);
auth.use('/anvisa', anvisa);
auth.use('/apuracaoICMS', apuracaoICMS);
auth.use('/atualizacaoPreco', atualizacaoPreco);
auth.use('/balancoGeral', balancoGeral);
auth.use('/banco', banco);
auth.use('/bico', bico);
auth.use('/boleto', boleto);
auth.use('/boletoWs', boletoWs);
auth.use('/bomba', bomba);
auth.use('/cargo', cargo);
auth.use('/cartao', cartao);
auth.use('/cartaoConvenio', cartaoConvenio);
auth.use('/centroCusto', centroCusto);
auth.use('/cep', cep);
auth.use('/cest', cest);
auth.use('/cfFarmaceutico', cfFarmaceutico);
auth.use('/cfop', cfop);
auth.use('/cheque', cheque);
auth.use('/cheque2', cheque2);
auth.use("/cidade", cidade);
auth.use('/classFiscal', classFiscal);
auth.use('/classFiscalImpressora', classFiscalImpressora);
auth.use('/clienteDescProduto', clienteDescProduto);
auth.use('/clienteEndereco', clienteEndereco);
auth.use("/clientes", clientes);
auth.use("/codBarra", codBarra);
auth.use("/compra4", compra4)
auth.use("/compraSugestao", compraSugestao);
auth.use('/compraSugestao2', compraSugestao2);
auth.use("/comunicacaoBico", comunicacaoBico);
auth.use('/condicaoPagamento', condicaoPagamento);
auth.use('/condicaoParcelamento', condicaoParcelamento);
auth.use('/configBoleto', configBoleto);
auth.use('/configSped', configSped);
auth.use('/conhecimentoTransporte', conhecimentoTransporte);
auth.use("/conta", conta);
auth.use('/contabilista', contabilista);
auth.use('/contaContabil', contaContabil);
auth.use('/contasPagar', contasPagar);
auth.use('/contasReceber', contasReceber);
auth.use('/cotacao', cotacao);
auth.use('/csosn', csosn);
auth.use('/cst', cst);
auth.use('/cstpiscofins', cstpiscofins);
auth.use('/cte', cte);
auth.use('/curvaABC', curvaABC);
auth.use('/dash', dash);
auth.use('/dav', dav);
auth.use('/dcbs', dcbs);
auth.use('/dependenteCliente', dependenteCliente);
auth.use('/ecfCupomCab', ecfCupomCab);
auth.use('/ecfImpressora', ecfImpressora);
auth.use('/ecfMovimento', ecfMovimento);
auth.use('/ecfReducao', ecfReducao);
auth.use('/emails', emails);
auth.use('/empresaConveniada', empresaConveniada);
auth.use('/encerrante', encerrante);
auth.use('/encomenda', encomenda);
auth.use('/encomendaCab', encomendaCab);
auth.use('/entrega', entrega);
auth.use('/escaneados', escaneados)
auth.use('/estacao', estacao);
auth.use("/estoque", estoque);
auth.use('/estoqueGeral', estoqueGeral);
auth.use('/etiqueta', etiqueta);
auth.use('/exportaBalanca', exportaBalanca);
auth.use('/exportacao', exportacao);
auth.use("/fabricante", fabricante);
auth.use('/faixaVencimento', faixaVencimento)
auth.use('/fatura', fatura);
auth.use('/fechamentoCaixa', fechamentoCaixa);
auth.use('/fornecedor', fornecedor);
auth.use("/funcionario", funcionario);
auth.use('/gerarLMC', gerarLMC);
auth.use('/grupoDescontoEmpresa', grupoDescontoEmpresa);
auth.use('/grupoPermissao', grupoPermissao);
auth.use('/grupoPreco', grupoPreco);
auth.use('/grupoProduto', grupoProduto);
auth.use('/grupoProibidoEmpresa', grupoProibidoEmpresa);
auth.use('/icms', icms);
auth.use('/impressora', impressora);
auth.use('/indicacao', indicacao)
auth.use('/infoComplementares', infoComplementares);
auth.use('/inventario', inventario);
auth.use('/lancamentoDiverso', lancamentoDiverso);
auth.use('/lancamentoFuncionario', lancamentoFuncionario);
auth.use('/lfInventario', lfInventario);
auth.use('/lfInventario2', lfInventario2);
auth.use('/lfInventario3', lfInventario3);
auth.use('/lmcDet', lmcDet);
auth.use('/lmcEstoque', lmcEstoque);
auth.use('/lmcInterven', lmcInterven);
auth.use('/lmcIntervenBico', lmcIntervenBico);
auth.use('/log', log);
auth.use('/logBuscaBico', logBuscaBico);
auth.use('/listaPositivo', listaPositivo);
auth.use('/listaPsico', listaPsico);
auth.use('/livroLMC', livroLMC);
auth.use('/loja', loja);
auth.use('/lote', lote);
auth.use('/MDFe', MDFe);
auth.use('/mensagem', mensagem);
auth.use('/menu', menu);
auth.use('/modelosFiscais', modelosFiscais);
auth.use('/movCartao', movCartao);
auth.use('/movConta', movConta);
auth.use('/movimentacaoCaixa', movimentacaoCaixa);
auth.use('/movimentacaoSNGPC', movimentacaoSNGPC);
auth.use('/movimentacaoSNGPC2', movimentacaoSNGPC2);
auth.use('/movimento', movimento);
auth.use('/msgCliente', msgCliente);
auth.use('/naturezaOP', naturezaOP);
auth.use('/naturezaReceita', naturezaReceita);
auth.use('/ncm', ncm);
auth.use('/ncmGenero', ncmGenero);
auth.use('/ncmPosicao', ncmPosicao);
auth.use('/ncmSecao', ncmSecao);
auth.use('/nfeCabecalho4', nfeCabecalho4);
auth.use('/notaM1', notaM1);
auth.use('/notaServico', notaServico);
auth.use('/observacao', observacao);
auth.use('/pbm', pbm);
auth.use('/pbms', pbms);
auth.use('/pedido', pedido);
auth.use('/periodoContabilista', periodoContabilista);
auth.use('/planoConta', planoConta);
auth.use('/prevenda', prevenda);
auth.use('/principioAtivo', principioAtivo);
auth.use('/produtoDlg', produtoDlg);
auth.use('/produtoFornecedor', produtoFornecedor);
auth.use('/produtoRapido', produtoRapido);
auth.use("/produtos", produtos);
auth.use('/produtoSecao', produtoSecao);
auth.use('/profSaude', profSaude);
auth.use('/promocao', promocao);
auth.use('/recarga', recarga);
auth.use('/receita', receita);
auth.use('/rede', rede);
auth.use('/registro60', registro60);
auth.use('/relatorio', relatorio);
auth.use('/segmento', segmento);
auth.use('/seried', seried);
auth.use('/servico', servico);
auth.use('/sintegra', sintegra);
auth.use('/sped', sped);
auth.use('/spedCofins', spedCofins);
auth.use('/subGrupoProduto', subGrupoProduto);
auth.use('/tanque', tanque);
auth.use('/tanqueMedicao', tanqueMedicao);
auth.use('/telecomunicacao', telecomunicacao);
auth.use('/tipoCombustivel', tipoCombustivel);
auth.use('/tipoDespesa', tipoDespesa);
auth.use('/tipoItem', tipoItem);
auth.use('/tipoPagto', tipoPagto);
auth.use('/tipoServico', tipoServico);
auth.use('/totalizador', totalizador);
auth.use('/transacao', transacao);
auth.use("/transportadora", transportadora);
auth.use('/turno', turno);
auth.use('/unidade', unidade);
auth.use("/usuario", usuario);
auth.use('/veiculo', veiculo);
auth.use('/ibpt', ibpt);
auth.use('/vendas', vendas);


auth.use("/db", mainRoute);

app.use("/api/v1/", auth); // api/v1/db

app.listen(port, "0.0.0.0", () => {
    console.log(`App running on port ${port}.`);
});
